name: .NET CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'
    - name: Restore dependencies
      run: dotnet restore AssignmentManagementApp.Tests.sln
    - name: Build
      run: dotnet build AssignmentManagementApp.Tests.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test AssignmentManagementApp.Tests.sln --configuration Release --no-build --verbosity normal
